version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: 'server_focus_zone'
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Roman13_D14AR
      POSTGRES_DB: cafe_db
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis: 
    image: redis:latest
    container_name: redis
    ports: 
      - "6379:6379"
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports: 
      - "3000:3000"
    volumes: 
      - .:/usr/src/app
    depends_on: 
      - postgres
      - redis
    environment:
      DATABASE_HOST: localhost
      DATABASE_PORT: 5432
      DATABASE_USER: postgres
      DATABASE_PASSWORD: Roman13_D14AR
      DATABASE_NAME: cafe_db
      DATABASE_URL: postgresql://Roman13_D14AR:postgres@db:5432/cafe_db
      REDIS_HOST: redis
      REDIS_PORT: 6379  
    command: sh -c "npx prisma migrate dev --name init && npm run start:dev"  
  
volumes:
  pgdata: